// Generate SQL from the versioned UI catalog; no API calls or user data.
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '../..');
const context = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(root, 'ranking-smash-ultimate/characters.js'), 'utf8'), context);
const catalog = vm.runInContext('CHARACTER_CATALOG', context);
const rows = [...catalog, {characterId:'1746',name:'Random Character',slug:'random',icon:null,portrait:null}];
const ids = new Set();
const quote = value => value == null ? 'NULL' : "'"+String(value).replace(/'/g,"''")+"'";
for (const row of rows) {
  if (!/^\d+$/.test(row.characterId) || ids.has(row.characterId)) throw Error('Invalid/duplicate character ID');
  if ([row.name,row.slug,row.icon,row.portrait].some(v=>typeof v==='string'&&/[\\\r\n\0]/.test(v))) throw Error('Unexpected SQL literal');
  ids.add(row.characterId);
}
const sql = '-- Generated by scripts/database/build_character_seed.cjs. Run AFTER schema.sql.\n'+
  '-- Repeatable: refreshes catalog labels/assets, never deletes player selections.\n'+
  'SET NAMES utf8mb4;\nINSERT INTO characters (id, name, slug, icon_url, portrait_url) VALUES\n'+
  rows.map(r=>'('+[r.characterId,quote(r.name),quote(r.slug),quote(r.icon),quote(r.portrait)].join(', ')+')').join(',\n')+
  '\nON DUPLICATE KEY UPDATE name=VALUES(name), slug=VALUES(slug), icon_url=VALUES(icon_url), portrait_url=VALUES(portrait_url);\n';
const destination=path.join(root,'docs/smash/seed-characters.sql');
const bundlePath=path.join(root,'docs/smash/install.sql');
const bundle=fs.readFileSync(path.join(root,'docs/smash/schema.sql'),'utf8')+'\n'+sql;
if(process.argv.includes('--check')){
  if(fs.readFileSync(destination,'utf8')!==sql || fs.readFileSync(bundlePath,'utf8')!==bundle) throw Error('Regenerate database SQL files');
}else{fs.writeFileSync(destination,sql);fs.writeFileSync(bundlePath,bundle);}
console.log(`${rows.length} character IDs verified`);
